name: Tests
on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.9 ]
    steps:
      - name: Set Up Git repository
        uses: actions/checkout@v2

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip list
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install antlr4
          elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install antlr4
          else
              brew install antlr
          fi
      - name: Run tests
        run: |
          pytest
